server:
  host: 10.121.212.10
  port: 7777
  processes: 1
  min_threads: 2
  max_threads: 4
  idle_thread_timeout: 300
  log_dir: log
  pid_dir: tmp/pids

site:
  name: Waxx
  support_email: support@waxx.io
  url: https://dev.waxx.io/

encryption:
  cipher: AES-256-CBC
  key: 6+j8f3wC.M+eS+xF1Xth~uBFP/W<&^12
  iv:  2x%)slli]IIR7;#S

cookie:
  user:
    name: u
    expires_after_login_mins: 1440
    expires_after_activity_mins: 480
    secure: true
  agent:
    name: a
    expires_years: 30
    secure: true

debug:
  level: 9
  on_screen: true
  send_email: false
  email: dan@eparklabs.com
  auto_reload_code: true

xdatabases:
  app: postgresql://waxx@localhost:5432/waxx

default:
  app: welcome
  act: index
  ext: html

smtp:
  server: aeromail.io
  user: system@waxx.io
  pass: gQBuv4akNRuq
  port: 465
  tls: true
  authentication: plain

file:
  serve: true
  path: public
